[project]
name = "magic-assistant"
description = "Say goodbye to clutter! ðŸš€ A suite of 'Integrated Nodes' to simplify your workflow. ðŸ¤– AI Node: Versatile role-play & rules with handy one-click presets! ðŸ§  Programmable Logic: An exclusive node to edit logic directlyâ€”handle all checks in ONE node without complex wiring! Simple & High Freedom! ðŸŒ Full Bilingual Support: All nodes support real-time Chinese/English language switching via floating switcher! ðŸŽ¨ More nodes await your discovery! å‘Šåˆ«çç¢Žè¿žçº¿ï¼ðŸš€ æœ¬æ’ä»¶ä¸“æ³¨äºŽâ€œå¤šåŠŸèƒ½é›†æˆèŠ‚ç‚¹â€ã€‚ðŸ¤– AIèŠ‚ç‚¹ï¼šé€šè¿‡è§’è‰²æ‰®æ¼”å’Œè§„åˆ™å¤„ç†å„ç§å·¥ä½œï¼Œè‡ªå¸¦å¥½ç”¨é¢„è®¾ï¼Œä¸€é”®ä¸Šæ‰‹ï¼ðŸ§  ç‹¬å®¶é€»è¾‘è®¡ç®—èŠ‚ç‚¹ï¼šæ”¯æŒè‡ªå®šä¹‰ç¼–è¾‘è®¡ç®—é€»è¾‘ï¼Œä¸€ä¸ªèŠ‚ç‚¹ç›´æŽ¥æžå®šæ‰€æœ‰æ¯”è¾ƒä¸Žè¿ç®—ç”šè‡³ä¸€é”®è¾“å‡ºï¼Œæ‹’ç»ç¹å¤æ“ä½œï¼ç®€å•æ˜“ç”¨ï¼Œè‡ªç”±åº¦æžé«˜ï¼ðŸŒ å®Œæ•´åŒè¯­æ”¯æŒï¼šæ‰€æœ‰èŠ‚ç‚¹å‡æ”¯æŒé€šè¿‡æ‚¬æµ®åˆ‡æ¢å™¨å®žæ—¶åˆ‡æ¢ä¸­è‹±æ–‡ç•Œé¢ï¼ðŸŽ¨ æ›´å¤šèŠ‚ç‚¹ç­‰ä½ å‘çŽ°ï¼"
version = "1.1.4"
license = {file = "LICENSE"} 
# classifiers = [
#     # For OS-independent nodes (works on all operating systems)
#     "Operating System :: OS Independent",
#
#     # OR for OS-specific nodes, specify the supported systems:
#     "Operating System :: Microsoft :: Windows",  # Windows specific
#     "Operating System :: POSIX :: Linux",  # Linux specific
#     "Operating System :: MacOS",  # macOS specific
#
#     # GPU Accelerator support. Pick the ones that are supported by your extension.
#     "Environment :: GPU :: NVIDIA CUDA",    # NVIDIA CUDA support
#     "Environment :: GPU :: AMD ROCm",       # AMD ROCm support
#     "Environment :: GPU :: Intel Arc",      # Intel Arc support
#     "Environment :: NPU :: Huawei Ascend",  # Huawei Ascend support
#     "Environment :: GPU :: Apple Metal",    # Apple Metal support
# ]

dependencies = ["openai", "aiohttp"]

[project.urls]
Repository = "https://github.com/shigjfg/ComfyUI-Magic-Assistant"
#  Used by Comfy Registry https://registry.comfy.org
Documentation = "https://github.com/shigjfg/ComfyUI-Magic-Assistant/wiki"
"Bug Tracker" = "https://github.com/shigjfg/ComfyUI-Magic-Assistant/issues"

[tool.comfy]
PublisherId = "shijun"
DisplayName = "ComfyUI-Magic-Assistant"
Icon = ""
includes = [] 
# "requires-comfyui" = ">=1.0.0"  # ComfyUI version compatibility

